### ISSUE TITLE
Make fetch call for food recipes

### ISSUE THREAD

**Issue by LWhitted** [LWhitted/FrontEnd-Project#2]

**Comment by Victoria-Contreras** [comment]
fetch a recipe by using the name of the dish 
example: 
www.themealdb.com/api/json/v1/1/search.php?s=pasta

response: 
*it only brings back one recipe so we don't need to do any iterations.*
"meals": [
   {
      "strMeal" : "Mediterranean Pasta Salad",
    ... (all the values we want to use are listed below this is just an example of the structure of the response)
   }
]


info we want: 
MEAL NAME
"strMeal" : "Mediterranean Pasta Salad", 

COOKING INSTRUCTIONS
"strInstructions" : "big paragraph of instructions",

MEAL PICTURE
"strMealThumb" : "mealImage.jpg",

INGREDIENTS
"strIngredient1": "mozzarella balls",
"strIngredient2": "baby plum tomatoes",
...
"strIngredient15": "",
"strIngredient16": null,

MEASUREMENTS
"strMeasure1": "200 g",
"strMeasure2": "250 g",
..
"strMeasure15": "",
"strMeasure16": null,
