### ISSUE TITLE
create readMe.md with details on project

### ISSUE THREAD

**Issue by LWhitted** [LWhitted/FrontEnd-Project#4]

**Comment by knsong1** [comment]
API1: https://www.themealdb.com/api.php
API2: https://www.thecocktaildb.com/api.php

Primary Necessities for Website: 

1. search bar that returns recipes/meals
2. eventlistener for search-form
3. card appears when meals are searched with images, ingredients and recommended alcoholic drink
4. card will have a separate info for recommended alcoholic drink (maybe in a footer area?) 

- ingredients for drinks should be included
- maybe we can create a fun button that they can click when the card appears that says "want a fun drink with this meal? Click here!"

5. alcoholic drink will be randomized for each meal
6. make sure that if a meal does not exist the search-bar has a response ("meal does not exist")
